[package]
name = "dkom_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.22.0"
anyhow = "1.0.95"
reqwest = { version = "0.12.10", features = ["blocking"] }
chrono = "0.4.39"
regex = "1.11.1"
pdf-extract = "0.7.11"