[package]
name = "dkom_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.21.0"
anyhow = "1.0.94"
reqwest = { version = "0.12.9", features = ["blocking"] }
lopdf = "0.34.0"
chrono = "0.4.38"
regex = "1.11.1"